version: "3.9"

networks:
  backend:

services:
  digital-menu-database:
    image: mariadb:10.9.5
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=qr_menu
    volumes:
      # - ./mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - service-mariadb:/var/lib/mysql
    command: ["--max_connections=1000"]
    ports:
      - 127.0.0.1:33066:3306
    networks:
      - backend

  digital-menu-backend:
    build:
      context: ./backend
      dockerfile: prod.Dockerfile
    ports:
      - 127.0.0.1:5008:5008
    networks:
      - backend
    depends_on:
      - digital-menu-database

volumes:
  service-mariadb:
